<h1>Категории</h1>
<table class="table table-striped table-hover">
    <tbody><tr>
        <th>#</th>
        <th>Ключ</th>
        <th>Название</th>
        <th>Действия</th>
    </tr>
    <?php
    foreach($category as $item) {
        echo "<tr>
            <td>{$item->getId()}</td>
             <td>{$item->getCategoryKey()}</td>
              <td>{$item->getCategoryName()}</td>";
        echo '<td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id' =>$item->getId())).'">Редактировать</a>&nbsp;&nbsp;
        <a href="'.$this->url('admin/category', array('action' => 'delete', 'id' =>$item->getId())).'">Удалить</a></td></tr>';
    }
    ?>
    </tbody>
</table>